# Generated by Django 2.2.16 on 2020-09-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testId', models.BigIntegerField()),
                ('name', models.BigIntegerField()),
            ],
        ),
    ]
